[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-fund --no-audit"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = [""], Country = ["!"], Language = [""]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment variables (these should be set in Netlify UI)
# VITE_FIREBASE_API_KEY
# VITE_FIREBASE_PROJECT_ID
# VITE_FIREBASE_APP_ID
# NODE_ENV

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://neetprep2025.netlify.app"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]

# Edge functions (if needed for future API endpoints)
# [[edge_functions]]
#   function = "api"
#   path = "/api/*"

# Form handling (if needed for contact/feedback forms)
# [forms]
#   hidden = ["_gotcha"]

# Large Media (if needed for large assets)
# [large_media]
#   enabled = true

# Build hooks (for scheduled rebuilds)
# [build.hooks]
#   name = "Daily rebuild"
#   url = "https://api.netlify.com/build_hooks/YOUR_HOOK_ID"
